language: java
jdk:
  - openjdk8

# Travis 를 어느 브랜치 Push 에 수행할 지 지정.
branches:
  only:
    - master

# Travis CI 서버의 Home
# gradle 을 통해 의존성을 받고 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포때 다시 받지 않도록.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시했을 때 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - 'harudamgi@naver.com'
